char *alocare_text(char *text,int dim);
void afisare_lista_jucatori(lista_jucatori *lista);
void afisare_lista_echipe(lista_echipe *lista);
lista_jucatori *creare_jucator(char *nume,char *prenume,int puncte);
void inserare_jucator(lista_jucatori **lista,char *numme,char *prenume,int puncte);
lista_echipe *creare_echipa(char *nume_echipa,float medie,int nr_jucatori,lista_jucatori *lista);
void inserare_echipa(lista_echipe **lista,char *nume_echipa,float medie,int nr_jucatori,lista_jucatori *player_list);
void stergere_lista_jucatori(lista_jucatori **lista);
void stergere_lista_echipe(lista_echipe **lista);
void stergere_lista_echipe_fara_lista_de_jucatori(lista_echipe **lista);
void citire_taskuri(int *taskuri);
void taskul1(lista_echipe **lista_cu_echipe,int *nr_echipe);
void fmm_backslash_n_la_final(lista_echipe **lista);
int suma_punctaje(lista_jucatori *aux);
void punctaj_minim(lista_echipe *lista,float *minim);
void eliminare_echipe_cu_punctaj_minim_din_stiva(lista_echipe **lista,lista_echipe *adresa);
void taskul2(lista_echipe **lista,int dif);
coada_meciuri *creaza_coada();
head_to_head *creare_meci(echipa t1,echipa t2);
void adaugare_meci_in_coada(coada_meciuri *program,echipa t1,echipa t2);
int puterea_maxima_a_lui_doi(int nr_echipe);
void afisare_lista_echipe_castigatorea_pt_fisier(lista_echipe *lista,int nr);
void afisare_program_meciuri_pt_fisier(coada_meciuri *program,int nr);
void taskul3(lista_echipe **lista,int *nr_echipe);
void iordine(Nod *root);
Nod* creare_nod_arbore(echipa team);
Nod* inserare_in_BTS(Nod *root,echipa team);
Nod* taskul4(lista_echipe *lista_cu_echipe);
int inaltime_arbore(Nod *root);
int indice_de_echilibru(Nod *root);
int maximul_dintre_doi_intregi(int a,int b);
Nod* rotatie_la_dreapta(Nod *z);
Nod* rotatie_la_stanga(Nod *z);
Nod *rotatie_la_stanga_dreapta(Nod *z);
Nod *rotatie_la_dreapta_stanga(Nod *z);
Nod* echilibrare_arbore(Nod *root);
void stergere_arbore(Nod *root);
void afisare_echipe_de_pe_nivelul_2(FILE *f,Nod *root);
Nod *taskul5(Nod *root);
